name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Tidy modules
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Build CLI
        run: go build -trimpath -ldflags "-s -w" ./cmd/ghostredact

      - name: Smoke test
        run: ./ghostredact -h || true
